### ISSUE TITLE
Crash on M1 Mac

### ISSUE THREAD

**Issue by beingalink** [s-a/sonic-sound-picture#1]
App Version: 1.0.8
Licensed: ?
Operating System: darwin 22.3.0

Error: Cannot read properties of undefined (reading 'qm-vamp-plugins')
Stack: TypeError: Cannot read properties of undefined (reading 'qm-vamp-plugins')
    at w.render (file:///Applications/ssp.app/Contents/Resources/app/.webpack/renderer/main_window/index.js:2:1283075)
    at Ps (file:///Applications/ssp.app/Contents/Resources/app/.webpack/renderer/main_window/index.js:2:173739)
    at Is (file:///Applications/ssp.app/Contents/Resources/app/.webpack/renderer/main_window/index.js:2:173537)
    at yl (file:///Applications/ssp.app/Contents/Resources/app/.webpack/renderer/main_window/index.js:2:216999)
    at vd (file:///Applications/ssp.app/Contents/Resources/app/.webpack/renderer/main_window/index.js:2:205032)
    at gd (file:///Applications/ssp.app/Contents/Resources/app/.webpack/renderer/main_window/index.js:2:204960)
    at ud (file:///Applications/ssp.app/Contents/Resources/app/.webpack/renderer/main_window/index.js:2:204823)
    at ad (file:///Applications/ssp.app/Contents/Resources/app/.webpack/renderer/main_window/index.js:2:201630)
    at ld (file:///Applications/ssp.app/Contents/Resources/app/.webpack/renderer/main_window/index.js:2:202019)
    at Ho (file:///Applications/ssp.app/Contents/Resources/app/.webpack/renderer/main_window/index.js:2:142937)

{"componentStack":"
    at w (file:///Applications/ssp.app/Contents/Resources/app/.webpack/renderer/main_window/index.js:2:1278903)
    at div
    at div
    at k (file:///Applications/ssp.app/Contents/Resources/app/.webpack/renderer/main_window/index.js:2:1283931)
    at div
    at div
    at N (file:///Applications/ssp.app/Contents/Resources/app/.webpack/renderer/main_window/index.js:2:1291597)
    at div
    at main
    at Y (file:///Applications/ssp.app/Contents/Resources/app/.webpack/renderer/main_window/index.js:2:1329488)
    at oe (file:///Applications/ssp.app/Contents/Resources/app/.webpack/renderer/main_window/index.js:2:1331523)
    at U (file:///Applications/ssp.app/Contents/Resources/app/.webpack/renderer/main_window/index.js:2:1303313)"}

**Comment by dinohusejnovic** [comment]
Seeing the same on an Intel mac
