### ISSUE TITLE
Error when trying to choose a template

### ISSUE THREAD

**Issue by FelleKing** [s-a/sonic-sound-picture#11]
Hi, just as the title says. It comes up with this message:

App Version: 1.0.15
Operating System: win32 10.0.19045

Error: Cannot read properties of undefined (reading 'username')
Stack: TypeError: Cannot read properties of undefined (reading 'username')
    at de.renderTemplateSelection (file:///C:/Users/Rasmu/AppData/Local/ssp/app-1.0.15/resources/app/.webpack/renderer/main_window/index.js:2:1348747)
    at de.render (file:///C:/Users/Rasmu/AppData/Local/ssp/app-1.0.15/resources/app/.webpack/renderer/main_window/index.js:2:1366760)
    at Ps (file:///C:/Users/Rasmu/AppData/Local/ssp/app-1.0.15/resources/app/.webpack/renderer/main_window/index.js:2:178154)
    at Is (file:///C:/Users/Rasmu/AppData/Local/ssp/app-1.0.15/resources/app/.webpack/renderer/main_window/index.js:2:177952)
    at kl (file:///C:/Users/Rasmu/AppData/Local/ssp/app-1.0.15/resources/app/.webpack/renderer/main_window/index.js:2:221287)
    at xd (file:///C:/Users/Rasmu/AppData/Local/ssp/app-1.0.15/resources/app/.webpack/renderer/main_window/index.js:2:209490)
    at hd (file:///C:/Users/Rasmu/AppData/Local/ssp/app-1.0.15/resources/app/.webpack/renderer/main_window/index.js:2:209418)
    at gd (file:///C:/Users/Rasmu/AppData/Local/ssp/app-1.0.15/resources/app/.webpack/renderer/main_window/index.js:2:209281)
    at id (file:///C:/Users/Rasmu/AppData/Local/ssp/app-1.0.15/resources/app/.webpack/renderer/main_window/index.js:2:206088)
    at dd (file:///C:/Users/Rasmu/AppData/Local/ssp/app-1.0.15/resources/app/.webpack/renderer/main_window/index.js:2:206477)

{"componentStack":"
    at de (file:///C:/Users/Rasmu/AppData/Local/ssp/app-1.0.15/resources/app/.webpack/renderer/main_window/index.js:2:1342833)
    at W (file:///C:/Users/Rasmu/AppData/Local/ssp/app-1.0.15/resources/app/.webpack/renderer/main_window/index.js:2:1313827)"}

I don't know if it will help any of you, but if it might it's worth posting.
Maybe I'm doing something wrong idk

**Comment by s-a** [comment]
This is already fixed in https://github.com/s-a/sonic-sound-picture/releases/tag/1.0.16. Please try this version.
