### ISSUE TITLE
ZeroDivisionError: float division by zero

### ISSUE THREAD

**Issue by s-a** [s-a/sonic-sound-picture#12]
This Happens when a audio file contains zero db amp value sections.

```bash
Error: Command failed with exit code 1: C:\Program Files\Blender Foundation\Blender 3.5\blender.exe --factory-startup --disable-autoexec --background C:\Users\steph\AppData\Roaming\ssp\templates\@john-doe\breathing-tile\template.blend --python-exit-code 1 --python C:\Users\steph\AppData\Local\ssp\app-1.0.17\resources\app\.webpack\renderer\static\render.py -- --working_directory C:\Users\steph\AppData\Local\Temp --session_id 7499b58878e53a0cd4d178837c565f395012d0e444a8c0e213e82a1d4221c9f9 --output_frames -1 --output_resolution 100 --output_using_compositor_node true --output_transparent false --output_fps 24 --output_resolution_x 1920 --output_resolution_y 1080 --input C:\Users\steph\Desktop\test\demo_mastered_mute --output_filename C:\Users\steph\Desktop\test\demo_mastered_mute_breathing-tile --output_type video Error: script failed, file: 'C:\Users\steph\AppData\Local\ssp\app-1.0.17\resources\app\.webpack\renderer\static\render.py', exiting. Blender 3.5.0 (hash 1be25cfff18b built 2023-03-29 06:36:20) Read blend: C:\Users\steph\AppData\Roaming\ssp\templates\@john-doe\breathing-tile\template.blend Error: Python: Traceback (most recent call last): File "<string>", line 1, in <module> File "C:\Users\steph\AppData\Local\ssp\app-1.0.17\resources\app\.webpack\renderer\static\render.py", line 529, in <module> scene_controller.write_frequency_band_info_key_frames(i, frequency_scale_max) File "C:\Users\steph\AppData\Local\ssp\app-1.0.17\resources\app\.webpack\renderer\static\render.py", line 309, in write_frequency_band_info_key_frames amp = round((amp / max_value) * frequency_scale_max, decimal_places) ZeroDivisionError: float division by zero
Command failed with exit code 1: C:\Program Files\Blender Foundation\Blender 3.5\blender.exe --factory-startup --disable-autoexec --background C:\Users\steph\AppData\Roaming\ssp\templates\@john-doe\breathing-tile\template.blend --python-exit-code 1 --python C:\Users\steph\AppData\Local\ssp\app-1.0.17\resources\app\.webpack\renderer\static\render.py -- --working_directory C:\Users\steph\AppData\Local\Temp --session_id 7499b58878e53a0cd4d178837c565f395012d0e444a8c0e213e82a1d4221c9f9 --output_frames -1 --output_resolution 100 --output_using_compositor_node true --output_transparent false --output_fps 24 --output_resolution_x 1920 --output_resolution_y 1080 --input C:\Users\steph\Desktop\test\demo_mastered_mute --output_filename C:\Users\steph\Desktop\test\demo_mastered_mute_breathing-tile --output_type video

Error: script failed, file: 'C:\Users\steph\AppData\Local\ssp\app-1.0.17\resources\app\.webpack\renderer\static\render.py', exiting.
Blender 3.5.0 (hash 1be25cfff18b built 2023-03-29 06:36:20)
Read blend: C:\Users\steph\AppData\Roaming\ssp\templates\@john-doe\breathing-tile\template.blend
Error: Python: Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Users\steph\AppData\Local\ssp\app-1.0.17\resources\app\.webpack\renderer\static\render.py", line 529, in <module>
    scene_controller.write_frequency_band_info_key_frames(i, frequency_scale_max)
  File "C:\Users\steph\AppData\Local\ssp\app-1.0.17\resources\app\.webpack\renderer\static\render.py", line 309, in write_frequency_band_info_key_frames
    amp = round((amp / max_value) * frequency_scale_max, decimal_places)
ZeroDivisionError: float division by zero
```

ref #11

**Comment by s-a** [comment]
fixed in https://github.com/s-a/sonic-sound-picture/releases/tag/1.0.17
