### ISSUE TITLE
Open Dialog fails on Mac

### ISSUE THREAD

**Issue by s-a** [s-a/sonic-sound-picture#2]
```
Uncaught Exception:
Error: Attempted to register a second handler for 'dialog:openDirectory'
at IpcMainImpl.handle (node:electron/js2c/browser_init:2:97331)
at c (/Applications/ssp.app/Contents/Resources/app/.webpack/main/index.js:14:100084)
at App.<anonymous> (/Applications/ssp.app/Contents/Resources/app/.webpack/main/index.js:14:100632)
at App.emit (node:events:513:28)
```

To work around the 1st setup step. Open `config.json` in application directory and edit the required path infos manually.

Blender path on mac?: 

select "View package contents" and selected Blender.app/Contents/MacOS/Blender 
as discussed here [1080223850077356062](https://discord.com/channels/1054281306055389304/1054281306055389310/1080223850077356062)

Effect unconfirmed

**Comment by s-a** [comment]
fixed in v1.0.10
