### ISSUE TITLE
SSP crashes after I select a template

### ISSUE THREAD

**Issue by magicaltrevor1970** [s-a/sonic-sound-picture#9]
App Version: 1.0.15
Operating System: win32 10.0.22621

Error: Cannot read properties of undefined (reading 'username')
Stack: TypeError: Cannot read properties of undefined (reading 'username')
    at de.renderTemplateSelection (file:///C:/Users/david/AppData/Local/ssp/app-1.0.15/resources/app/.webpack/renderer/main_window/index.js:2:1348747)
    at de.render (file:///C:/Users/david/AppData/Local/ssp/app-1.0.15/resources/app/.webpack/renderer/main_window/index.js:2:1366760)
    at Ps (file:///C:/Users/david/AppData/Local/ssp/app-1.0.15/resources/app/.webpack/renderer/main_window/index.js:2:178154)
    at Is (file:///C:/Users/david/AppData/Local/ssp/app-1.0.15/resources/app/.webpack/renderer/main_window/index.js:2:177952)
    at kl (file:///C:/Users/david/AppData/Local/ssp/app-1.0.15/resources/app/.webpack/renderer/main_window/index.js:2:221287)
    at xd (file:///C:/Users/david/AppData/Local/ssp/app-1.0.15/resources/app/.webpack/renderer/main_window/index.js:2:209490)
    at hd (file:///C:/Users/david/AppData/Local/ssp/app-1.0.15/resources/app/.webpack/renderer/main_window/index.js:2:209418)
    at gd (file:///C:/Users/david/AppData/Local/ssp/app-1.0.15/resources/app/.webpack/renderer/main_window/index.js:2:209281)
    at id (file:///C:/Users/david/AppData/Local/ssp/app-1.0.15/resources/app/.webpack/renderer/main_window/index.js:2:206088)
    at dd (file:///C:/Users/david/AppData/Local/ssp/app-1.0.15/resources/app/.webpack/renderer/main_window/index.js:2:206477)

{"componentStack":"
    at de (file:///C:/Users/david/AppData/Local/ssp/app-1.0.15/resources/app/.webpack/renderer/main_window/index.js:2:1342833)
    at W (file:///C:/Users/david/AppData/Local/ssp/app-1.0.15/resources/app/.webpack/renderer/main_window/index.js:2:1313827)"}

**Comment by EldritchBlackfish** [comment]
Same problem here

**Comment by Arzuck** [comment]
Same problem

App Version: 1.0.15
Operating System: win32 10.0.22621

Error: Cannot read properties of undefined (reading 'username')
Stack: TypeError: Cannot read properties of undefined (reading 'username')
    at de.renderTemplateSelection (file:///C:/Users/arzoc/AppData/Local/ssp/app-1.0.15/resources/app/.webpack/renderer/main_window/index.js:2:1348747)
    at de.render (file:///C:/Users/arzoc/AppData/Local/ssp/app-1.0.15/resources/app/.webpack/renderer/main_window/index.js:2:1366760)
    at Ps (file:///C:/Users/arzoc/AppData/Local/ssp/app-1.0.15/resources/app/.webpack/renderer/main_window/index.js:2:178154)
    at Is (file:///C:/Users/arzoc/AppData/Local/ssp/app-1.0.15/resources/app/.webpack/renderer/main_window/index.js:2:177952)
    at kl (file:///C:/Users/arzoc/AppData/Local/ssp/app-1.0.15/resources/app/.webpack/renderer/main_window/index.js:2:221287)
    at xd (file:///C:/Users/arzoc/AppData/Local/ssp/app-1.0.15/resources/app/.webpack/renderer/main_window/index.js:2:209490)
    at hd (file:///C:/Users/arzoc/AppData/Local/ssp/app-1.0.15/resources/app/.webpack/renderer/main_window/index.js:2:209418)
    at gd (file:///C:/Users/arzoc/AppData/Local/ssp/app-1.0.15/resources/app/.webpack/renderer/main_window/index.js:2:209281)
    at id (file:///C:/Users/arzoc/AppData/Local/ssp/app-1.0.15/resources/app/.webpack/renderer/main_window/index.js:2:206088)
    at dd (file:///C:/Users/arzoc/AppData/Local/ssp/app-1.0.15/resources/app/.webpack/renderer/main_window/index.js:2:206477)

{"componentStack":"
    at de (file:///C:/Users/arzoc/AppData/Local/ssp/app-1.0.15/resources/app/.webpack/renderer/main_window/index.js:2:1342833)
    at W (file:///C:/Users/arzoc/AppData/Local/ssp/app-1.0.15/resources/app/.webpack/renderer/main_window/index.js:2:1313827)"}

**Comment by s-a** [comment]
Ty for reporting this . This is fixed in https://github.com/s-a/sonic-sound-picture/releases/tag/1.0.16 now
